### ISSUE TITLE
assert x_t.shape == eps.shape

### ISSUE THREAD

**Issue by 2039551625** [MedicineToken/MedSegDiff#201]
你好，我在对于DRIVE数据集上进行采样时，出现了这样问题，请问我该如何解决呢
Traceback (most recent call last):
  File "E:\deep_learning\Segmentation\MedSegDiff-master\scripts\segmentation_sample.py", line 214, in <module>
    main()
  File "E:\deep_learning\Segmentation\MedSegDiff-master\scripts\segmentation_sample.py", line 123, in main
    sample, x_noisy, org, cal, cal_out = sample_fn(
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 565, in p_sample_loop_known
    for sample in self.p_sample_loop_progressive(
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 650, in p_sample_loop_progressive
    out = self.p_sample(
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 444, in p_sample
    out = self.p_mean_variance(
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\respace.py", line 90, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 324, in p_mean_variance
    self._predict_xstart_from_eps(x_t=x, t=t, eps=model_output)
  File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 348, in _predict_xstart_from_eps
    assert x_t.shape == eps.shape
AssertionError

**Comment by Coder-li-jiahao** [comment]
same question

**Comment by Coder-li-jiahao** [comment]
> 你好，我在对于DRIVE数据集上进行采样时，出现了这样问题，请问我该如何解决呢 Traceback (most recent call last): File "E:\deep_learning\Segmentation\MedSegDiff-master\scripts\segmentation_sample.py", line 214, in main() File "E:\deep_learning\Segmentation\MedSegDiff-master\scripts\segmentation_sample.py", line 123, in main sample, x_noisy, org, cal, cal_out = sample_fn( File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 565, in p_sample_loop_known for sample in self.p_sample_loop_progressive( File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 650, in p_sample_loop_progressive out = self.p_sample( File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 444, in p_sample out = self.p_mean_variance( File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\respace.py", line 90, in p_mean_variance return super().p_mean_variance(self._wrap_model(model), *args, **kwargs) File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 324, in p_mean_variance self._predict_xstart_from_eps(x_t=x, t=t, eps=model_output) File "E:\deep_learning\Segmentation\MedSegDiff-master\guided_diffusion\gaussian_diffusion.py", line 348, in _predict_xstart_from_eps assert x_t.shape == eps.shape AssertionError

same question

**Comment by 2039551625** [comment]
我尝试打印他们的形状，分别为x_t: torch.Size([1, 1, 64, 64]),eps: torch.Size([1, 2, 64, 64])，然后我打印出eps中的数据，发现他的两个通道的数据是一样的，所以我将eps就只取了第一通道，就跑通了

**Comment by 2039551625** [comment]
但是我对于问题出现的原因，还是存有我的疑问

**Comment by Coder-li-jiahao** [comment]
> 但是我对于问题出现的原因，还是存有我的疑问

How is your segmentation effect? After running this experiment, I feel that the segmentation results are not as good as UNet

**Comment by Coder-li-jiahao** [comment]
> 我尝试打印他们的形状，分别为x_t: torch.Size([1, 1, 64, 64]),eps: torch.Size([1, 2, 64, 64])，然后我打印出eps中的数据，发现他的两个通道的数据是一样的，所以我将eps就只取了第一通道，就跑通了

My solution is the same as yours

**Comment by 2039551625** [comment]
但是我跑出的效果有点差
![12_test_output_ens](https://github.com/user-attachments/assets/dd2ebd59-2d12-4a56-a0c4-47de089e6cb6)

**Comment by 2039551625** [comment]
请问你跑的数据集上的效果怎么样

**Comment by Coder-li-jiahao** [comment]
> 请问你跑的数据集上的效果怎么样

My results were also very poor

**Comment by 123YanHaochen** [comment]
兄弟，你大约训了多少步到达这个效果的？



> 但是我跑出的效果有点差 ![12_test_output_ens](https://github.com/user-attachments/assets/dd2ebd59-2d12-4a56-a0c4-47de089e6cb6)

**Comment by 2039551625** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> Brother, how many steps have you trained to achieve this effect?
> 
> > But the effect I ran was a bit bad![12_test_output_ens](https://github.com/user-attachments/assets/dd2ebd59-2d12-4a56-a0c4-47de089e6cb6)

应该是10000左右
